### ISSUE TITLE
shutdownsignal exception when reconnecting

### ISSUE THREAD

**Issue by zeitos** [jhalterman/lyra#46]
I'm seeing this error right after the rabbit server goes back to life:
```
DefaultExceptionHandler: Consumer com.rabbitmq.client.QueueingConsumer@271d2d04 (amq.ctag-cYQcdbtkNo_ZIAoqHEU52A) method handleDelivery for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1) threw an exception for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1):
com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.QueueingConsumer.checkShutdown(QueueingConsumer.java:172)
	at com.rabbitmq.client.QueueingConsumer.handleDelivery(QueueingConsumer.java:124)
	at net.jodah.lyra.internal.ConsumerDelegate.handleDelivery(ConsumerDelegate.java:53)
```
any idea of what might be going on?

config:
```
config = config.withRecoveryPolicy(new RecoveryPolicy()
                        .withBackoff(Duration.seconds(1), Duration.minutes(10)));

        ConnectionOptions options = new ConnectionOptions()
                .withHost(hostname)
                .withPort(port)
                .withVirtualHost(virtualHost)
                .withUsername(username)
                .withPassword(password)
```

**Comment by zeitos** [comment]
looks like we can recover the channel but not the consumer
```
2015-03-05 15:02:44,559 (lyra-recovery-1) [INFO - net.jodah.lyra.internal.ChannelHandler$2.call(ChannelHandler.java:220)] Recovering channel-1 on cxn-1
2015-03-05 15:02:44,560 (lyra-recovery-1) [INFO - net.jodah.lyra.internal.ChannelHandler$2.call(ChannelHandler.java:224)] Recovered channel-1 on cxn-1
2015-03-05 15:02:44,560 (lyra-recovery-1) [INFO - net.jodah.lyra.internal.ChannelHandler.recoverConsumers(ChannelHandler.java:430)] Recovering consumer-amq.ctag-bcHQrzoj39VpG4yvuBS4DA of OutQueue via channel-1 on cxn-1
```

**Comment by zeitos** [comment]
I was using a QueueingConsumer, verifying that that's the issue

**Comment by zeitos** [comment]
that was the issue, closing

**Comment by jhalterman** [comment]
@zeitos I haven't tried QueueingConsumer with Lyra since it's deprecated. I'm away from my computer at the moment, but it looks like QueueingConsumer doesn't like to be recovered once a failure occurs. This is similar to how RpcClient behaves. Have a look at this recipe for using RpcClient - perhaps a similar approach can be used for QueueingConsumer:

https://github.com/jhalterman/lyra/wiki/Lyra-Cookbook#recoverable-rpcclient

If you try it out - let me know how it goes!

**Comment by zeitos** [comment]
I ended up extending DefaultConsumer and removing queuingConsumer :D
Thanks for your suggestion.

**Comment by michaelklishin** [comment]
It's not deprecated any more but yes, recovering is not supported (or possible, depending on who you ask) given its semantics and implementation details.
