### ISSUE TITLE
Lyra recover mechanism prevent from the JVM to shutdown

### ISSUE THREAD

**Issue by dimagol1989** [jhalterman/lyra#80]
After Lyra recovers the connections. the JVM won't exists (also the runtime shutdown won't start)
When running this small code without starting the recover mechanism, the JVM exists fine, and the line _"From shutdown hook"_ is printed out.
While running the code in debug mode do the following:

1. Breakpoint the code on line `Thread.sleep(2000);`
2. Restart the RabbitMQ service: `sudo service rabbitmq-server restart`
3. Continue the run of the code

After the last line, the JVM keeps hanging there and we can see that the line _"From shutdown hook"_ is NOT printed out, those, the shutdown hook did not started.

```
    public static void main(String[] args) throws Throwable {
        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            @Override
            public void run() {
                log.info("From shutdown hook");
            }
        }));

        Config config = new Config()
                .withRecoveryPolicy(RecoveryPolicies.recoverAlways())
                .withRetryPolicy(new RetryPolicy()
                        .withMaxAttempts(20)
                        .withInterval(Duration.seconds(1))
                        .withMaxDuration(Duration.minutes(5)));

        ConnectionOptions options = new ConnectionOptions().withHost("localhost");
        Connection connection = Connections.create(options, config);
        Channel channel = connection.createChannel();

        Thread.sleep(2000);

        channel.close();
        connection.close();

        Thread.sleep(1000);
    }
```

**Normal run output:**
```
18:00:47.227 [main] INFO  n.j.lyra.internal.ConnectionHandler - Creating connection cxn-1 to [localhost:5672]
18:00:47.364 [main] INFO  n.j.lyra.internal.ConnectionHandler - Created connection cxn-1 to amqp://127.0.0.1:5672/
18:00:47.423 [main] INFO  n.j.lyra.internal.ConnectionHandler - Created channel-1 on cxn-1
18:00:50.444 [Thread-0] INFO  net.jodah.lyra.test - From shutdown hook

Process finished with exit code 0
```

**With recovery output:**
```
18:02:04.779 [main] INFO  n.j.lyra.internal.ConnectionHandler - Creating connection cxn-1 to [localhost:5672]
18:02:04.932 [main] INFO  n.j.lyra.internal.ConnectionHandler - Created connection cxn-1 to amqp://127.0.0.1:5672/
18:02:05.024 [main] INFO  n.j.lyra.internal.ConnectionHandler - Created channel-1 on cxn-1
18:02:19.949 [AMQP Connection 127.0.0.1:5672] ERROR n.jodah.lyra.internal.ChannelHandler - Channel channel-1 on cxn-1 was closed unexpectedly
18:02:19.956 [AMQP Connection 127.0.0.1:5672] WARN  c.r.c.impl.ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Connection reset)
18:02:19.959 [AMQP Connection 127.0.0.1:5672] ERROR n.j.lyra.internal.ConnectionHandler - Connection cxn-1 was closed unexpectedly
18:02:19.962 [lyra-recovery-1] INFO  n.j.lyra.internal.ConnectionHandler - Recovering connection cxn-1 to [localhost:5672]
18:02:19.968 [lyra-recovery-1] INFO  n.j.lyra.internal.ConnectionHandler - Recovered connection cxn-1 to amqp://127.0.0.1:5672/
18:02:19.971 [lyra-recovery-1] INFO  n.jodah.lyra.internal.ChannelHandler - Recovering channel-1 on cxn-1
18:02:19.973 [lyra-recovery-1] INFO  n.jodah.lyra.internal.ChannelHandler - Recovered channel-1 on cxn-1
```

**With recovery thread dump:**
```
"pool-1-thread-10@1461" prio=5 tid=0x1a nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:748)

"lyra-recovery-1@1444" prio=5 tid=0x14 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	  at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	  at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:748)

"AMQP Connection 127.0.0.1:5672@1460" prio=5 tid=0x19 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	  at java.net.SocketInputStream.read(SocketInputStream.java:171)
	  at java.net.SocketInputStream.read(SocketInputStream.java:141)
	  at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	  - locked <0x5bb> (a java.io.BufferedInputStream)
	  at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	  at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	  at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	  - locked <0x5bc> (a java.io.DataInputStream)
	  at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571)
	  at java.lang.Thread.run(Thread.java:748)

"Finalizer@1465" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler@1466" daemon prio=10 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"DestroyJavaVM@1459" prio=5 tid=0x18 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"Signal Dispatcher@1464" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
```

**Comment by dimagol1989** [comment]
Started to debug this.
added to the lyra code in `ConnectionHandler` a small list to hold all the "new" delegates that been created 
in line 225 (`ConnectionHandler#createConnection` function)
Found that, after a recovery, a new connection is been created (this is fine) but the old one is still "alive" because of the `automaticRecovery` flag is `true` in the `ConnectionFactory` class.
Tried to set it to false, seems to be working, the JVM does shuts down. but not right away. 
any idea why?

**Comment by michaelklishin** [comment]
Because Java client starting with 4.0 enables automatic recovery by default and uses non-daemon threads (also by default). Lyra should disable automatic recovery in the Java client because it performs its own.

**Comment by michaelklishin** [comment]
@acogoluegnes there is a way to reproduce here. We will look into adding a new property, just like in the Java client.

**Comment by acogoluegnes** [comment]
There's a [static executor service](https://github.com/jhalterman/lyra/blob/19028fd83c9a47801b23e5f3be23a0256467aeb9/src/main/java/net/jodah/lyra/internal/ConnectionHandler.java#L42-L43) that is never shut down. With a modified version of @DimaGolomozy's test, the JVM shutdown after 1 minute, which is the default value of keep-alive time for the executor service.
Not sure how to fix this without regression.

**Comment by acogoluegnes** [comment]
My bad, the executor service is [shut down in shutdown hook](https://github.com/jhalterman/lyra/blob/19028fd83c9a47801b23e5f3be23a0256467aeb9/src/main/java/net/jodah/lyra/internal/ConnectionHandler.java#L61-L67). Chicken-and-egg problem.

**Comment by acogoluegnes** [comment]
https://github.com/jhalterman/lyra/pull/83 should do part of the job, but #84 is the biggest problem. There may also other cases where the executor service used for connections is not correctly closed.
